# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Repository-specific override
reviews:
  profile: assertive # assertive / chill profile
  auto_review:
    enabled: true # Enable auto-review for this repository
