# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""systemd user service for the CloudXR service.

Renders and manages ``~/.config/systemd/user/isaacteleop-cloudxr.service``.
Nothing here needs root: ``systemctl --user`` acts on the calling user's own
manager.  Surviving logout is the exception — see :func:`linger_hint`.
"""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

UNIT_NAME = "isaacteleop-cloudxr.service"

# StartLimit* live in [Unit], not [Service], since systemd 230.
#
# Restart=on-failure, not always: a rejected EULA and the --setup-oob adb
# preflights both exit non-zero with no headset attached, which is the normal
# state at boot, and `always` would turn that into a restart loop.
_UNIT_TEMPLATE = """\
# Generated by `python -m isaacteleop.cloudxr.service install`. Re-rendered on
# every install; put local changes in a drop-in instead:
#     systemctl --user edit {unit_name}
[Unit]
Description=Isaac Teleop CloudXR runtime and WSS proxy
Documentation=https://github.com/NVIDIA/IsaacTeleop
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=120
StartLimitBurst=3

[Service]
Type=simple
ExecStart={exec_start}
Restart=on-failure
RestartSec=5
Environment=PATH={path}
EnvironmentFile=-%h/.config/isaacteleop/cloudxr.env

[Install]
WantedBy=default.target
"""

_UNIT_PATH_ENV = "/usr/local/bin:/usr/bin:/bin"


def unit_dir() -> Path:
    """Directory holding user units."""
    return Path(os.path.expanduser("~/.config/systemd/user"))


def unit_path() -> Path:
    """Full path of the rendered unit file."""
    return unit_dir() / UNIT_NAME


def is_available() -> bool:
    """Whether this user has a reachable ``systemd --user`` manager.

    Containers and CI runners typically do not: PID 1 is the entrypoint, so
    the per-user manager never starts and its private socket is absent.
    """
    if shutil.which("systemctl") is None:
        return False
    # The manager's private socket, not `systemctl --user is-system-running`:
    # that reports "offline" and still exits 0 where there is no systemd at all.
    # XDG_RUNTIME_DIR is unset in cron and some non-login shells, so fall back
    # to the path logind would have used.
    runtime_dir = os.environ.get("XDG_RUNTIME_DIR") or f"/run/user/{os.getuid()}"
    return os.path.exists(os.path.join(runtime_dir, "systemd", "private"))


def is_installed() -> bool:
    """Whether the unit file exists."""
    return unit_path().is_file()


def render_unit(run_args: list[str]) -> str:
    """Render the unit, with *run_args* appended to the ``service run`` command.

    ``sys.executable`` is captured here rather than resolved at start time, so
    a unit always points at the interpreter that installed it.
    """
    exec_start = " ".join(
        shlex.quote(part)
        for part in [sys.executable, "-m", "isaacteleop.cloudxr.service", "run"]
        + run_args
    )
    return _UNIT_TEMPLATE.format(
        unit_name=UNIT_NAME, exec_start=exec_start, path=_UNIT_PATH_ENV
    )


def write_unit(run_args: list[str]) -> Path:
    """Render and write the unit file, then reload the manager."""
    path = unit_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_unit(run_args), encoding="utf-8")
    systemctl("daemon-reload")
    return path


def remove_unit() -> bool:
    """Delete the unit file and reload; return whether a file was removed."""
    path = unit_path()
    try:
        path.unlink()
    except FileNotFoundError:
        return False
    systemctl("daemon-reload")
    return True


def systemctl(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    """Run ``systemctl --user`` with *args*."""
    return subprocess.run(
        ["systemctl", "--user", *args], check=check, text=True, capture_output=True
    )


def enable_now() -> None:
    """Enable the unit and start it."""
    systemctl("enable", "--now", UNIT_NAME)


def disable_now() -> None:
    """Stop and disable the unit; tolerate it not being loaded."""
    systemctl("disable", "--now", UNIT_NAME, check=False)


def linger_hint() -> str:
    """Command that makes the service survive logout and start at boot."""
    return f"sudo loginctl enable-linger {os.environ.get('USER', '$USER')}"


def unavailable_message(reason: str) -> str:
    """Explain that systemd is unusable here, and what to do instead."""
    return (
        f"{reason}\n"
        "  This host has no reachable `systemd --user` manager (containers and "
        "CI runners normally do not).\n"
        "  Start the service yourself instead, either:\n"
        "    - run `python -m isaacteleop.cloudxr.service run` alongside your "
        "application (a container ENTRYPOINT is the usual place), or\n"
        "    - pass run_embedded=True to CloudXRLauncher so the calling process "
        "owns it."
    )
